service: dall-e-serverless

frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30

  stage: dev
  region: us-east-1

  environment:
    S3_BUCKET: dall-e-serverless-s3-${self:provider.stage}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource: arn:aws:s3:::${self.provider.environment.S3_BUCKET}/*

functions:
  GetImages:
    handler: src/functions/getImages.handler
    events:
      - http:
          method: get
          path: images
          cors: true
  GetSuggestion:
    handler: src/functions/getSuggestion.handler
    events:
      - http:
          method: get
          path: suggestion
          cors: true
  GenerateImage:
    handler: src/functions/generateImage.handler
    events:
      - http:
          method: post
          path: generate
          cors: true

resources:
  Resources:
    DallEBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.S3_BUCKET}
        AccessControl: PublicReadWrite
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000
